project:
  type: book
  output-dir: _book
execute:
  warning: false
  freeze: auto



book:
  title: "Simulasi Makro"
  author: "Andi Hermanto"
  date: "20/09/2025"
  page-footer:
      left: |
        An open-source platform for macroeconomic model simulation. 
      right: |
        <a>License: ...<a/> <a href="https://github.com/hermantoXYZ/Simulasi-Makro#">Source code</a>

  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
    - part: "Static Models"
      chapters:
        - intro.qmd
    - part: "Dynamic Models"
      chapters:
        - intro.qmd


  sidebar: 
    style: "floating"
    search: true

bibliography: references.bib

format:
  html:
    toc: true
    toc-depth: 5
    number-depth: 1
    theme:
      dark: darkly
      light: cosmo
    code-link: true
    code-copy: true
    
editor: source

df-print: paged